FROM python:3.9

ARG user=lbry
ARG downloads_dir=/database
ARG projects_dir=/home/$user

ARG DOCKER_TAG
ARG DOCKER_COMMIT=docker
ENV DOCKER_TAG=$DOCKER_TAG DOCKER_COMMIT=$DOCKER_COMMIT

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
      pipx \
      wget \
      automake libtool \
      tar unzip \
      build-essential \
      pkg-config && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd -g 999 $user && useradd -m -u 999 -g $user $user
RUN mkdir -p $downloads_dir
RUN chown -R $user:$user $downloads_dir

COPY scripts/ $projects_dir/scripts/
COPY setup* $projects_dir
COPY Makefile* $projects_dir
COPY lbry/ $projects_dir/lbry/
COPY tests/ $projects_dir/tests/
COPY icons/ $projects_dir/icons/
COPY docker/set_build.py $projects_dir/docker/set_build.py
COPY *.md $projects_dir/
RUN chown -R $user:$user $projects_dir

USER $user
WORKDIR $projects_dir

RUN pipx install uv
RUN pip install uvloop
RUN make install
RUN python3 docker/set_build.py
RUN rm ~/.cache -rf

# entry point
VOLUME $downloads_dir
COPY ./docker/webconf.yaml /webconf.yaml
ENTRYPOINT ["/home/lbry/.local/bin/lbrynet", "start", "--config=/webconf.yaml"]
